"""expression added

Revision ID: 31c49e82a577
Revises: ad692095871f
Create Date: 2025-03-05 20:43:00.832725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c49e82a577'
down_revision: Union[str, None] = 'ad692095871f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by yousri! ###
    op.add_column('formulas', sa.Column('expression', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'expression')
    # ### end Alembic commands ###