"""inputs table added

Revision ID: ad692095871f
Revises: d9cb9015e08f
Create Date: 2025-03-05 19:37:41.355008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad692095871f'
down_revision: Union[str, None] = 'd9cb9015e08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by yousri ! ###
    op.create_table('formula_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_inputs_id'), 'formula_inputs', ['id'], unique=False)
    op.add_column('formulas', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('formulas_category_id_fkey', 'formulas', type_='foreignkey')
    op.create_foreign_key(None, 'formulas', 'categories', ['category_id'], ['id'])
    op.drop_column('formulas', 'variables')
    op.drop_column('formulas', 'logic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('logic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('formulas', sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.create_foreign_key('formulas_category_id_fkey', 'formulas', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('formulas', 'description')
    op.drop_index(op.f('ix_formula_inputs_id'), table_name='formula_inputs')
    op.drop_table('formula_inputs')
    # ### end Alembic commands ###