"""category added

Revision ID: fd276d166077
Revises: a77f07604e24
Create Date: 2025-03-05 15:23:12.899466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd276d166077'
down_revision: Union[str, None] = 'a77f07604e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('formulas', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.alter_column('formulas', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('formulas', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('formulas', 'logic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('formulas_creator_id_fkey', 'formulas', type_='foreignkey')
    op.create_foreign_key(None, 'formulas', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.create_foreign_key('formulas_creator_id_fkey', 'formulas', 'users', ['creator_id'], ['id'])
    op.alter_column('formulas', 'logic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formulas', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('formulas', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('formulas', 'usage_count')
    # ### end Alembic commands ###